;; MinhChien Custom Modern Topbar Palette

[color]
background = #1e1e2e
foreground = #cdd6f4
background-alt = #313244
foreground-alt = #bac2de

;; Pastel Accents
lavender = #cba6f7
pink = #f5c2e7
rosewater = #f5e0dc
flamingo = #f2cdcd
red = #f38ba8
maroon = #eba0ac
peach = #fab387
yellow = #f9e2af
green = #a6e3a1
teal = #94e2d5
sky = #89dceb
sapphire = #74c7ec
blue = #89b4fa
comment = #6c7086
alpha = #00000000
