;; MinhChien Custom Modern Floating Topbar

[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/polybar/minhchien/colors.ini
include-file = ~/.config/polybar/minhchien/modules.ini

[bar/top]
monitor =
monitor-fallback =
monitor-strict = false

override-redirect = true
wm-restack = i3

bottom = false
fixed-center = true

width = 98%
height = 34

offset-x = 1%
offset-y = 8

background = ${color.background}
foreground = ${color.foreground}

radius = 12.0

border-size = 2
border-color = ${color.background-alt}

padding = 1

module-margin-left = 1
module-margin-right = 1

font-0 = "VictorMono Nerd Font:style=Bold:pixelsize=10;3"
font-1 = "VictorMono Nerd Font:style=Bold:pixelsize=12;3"
font-2 = "VictorMono Nerd Font:pixelsize=14;4"

modules-left = mascot i3 title
modules-center = date
modules-right = cpu memory pulseaudio brightness battery sysmenu

separator = " "

dim-value = 1.0
wm-name = polybar_topbar

tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 2
tray-scale = 1.0

enable-ipc = true

cursor-click = pointer
cursor-scroll = ns-resize

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = true
pseudo-transparency = true
